name: Selenium Headless URL Poster (Windows)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (GitHub's minimum interval)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-selenium:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install selenium requests

      - name: Install Stable Chrome
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe" -OutFile chrome_installer.exe
          Start-Process -FilePath chrome_installer.exe -ArgumentList "/silent /install" -NoNewWindow -Wait
        shell: powershell

      - name: Install ChromeDriver (Stable Version)
        run: |
          # Get stable Chrome version (Manually specify if needed)
          $chromeVersion = "134.0.6998.89"  # <- Adjust this if needed
          $chromeMajorVersion = $chromeVersion.Split('.')[0]
          
          # Fetch correct ChromeDriver version
          $chromeDriverVersionUrl = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_" + $chromeMajorVersion
          $chromeDriverVersion = Invoke-RestMethod -Uri $chromeDriverVersionUrl
          $chromeDriverUrl = "https://chromedriver.storage.googleapis.com/" + $chromeDriverVersion + "/chromedriver_win32.zip"

          Invoke-WebRequest -Uri $chromeDriverUrl -OutFile "chromedriver.zip"
          Expand-Archive -Path chromedriver.zip -DestinationPath C:\chromedriver
          echo "C:\chromedriver" | Out-File -Append -Encoding ascii $env:GITHUB_PATH
        shell: powershell

      - name: Run Selenium Script
        run: python send_report.py
