name: Selenium Headless URL Poster (Windows)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # GitHub's minimum interval (5 min)
  workflow_dispatch:  # Manual trigger

jobs:
  run-selenium:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install selenium requests

      - name: Download and Install Chrome (Stable)
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile chrome_installer.exe
          Start-Process -FilePath chrome_installer.exe -ArgumentList "/silent /install" -NoNewWindow -Wait
        shell: powershell

      - name: Install ChromeDriver (Matching Stable Chrome Version)
        run: |
          $chromePath = "C:\Program Files\Google\Chrome\Application\chrome.exe"
          if (!(Test-Path $chromePath)) {
              Write-Host "Chrome is not installed properly!"
              exit 1
          }
          
          $chromeVersion = (Get-Item $chromePath).VersionInfo.ProductVersion
          $chromeMajorVersion = $chromeVersion.Split('.')[0]
          
          # Fetch correct ChromeDriver version
          $chromeDriverVersionUrl = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_" + $chromeMajorVersion
          $chromeDriverVersion = Invoke-RestMethod -Uri $chromeDriverVersionUrl
          $chromeDriverUrl = "https://chromedriver.storage.googleapis.com/" + $chromeDriverVersion + "/chromedriver_win32.zip"

          Invoke-WebRequest -Uri $chromeDriverUrl -OutFile "chromedriver.zip"
          Expand-Archive -Path chromedriver.zip -DestinationPath C:\chromedriver
          echo "C:\chromedriver" | Out-File -Append -Encoding ascii $env:GITHUB_PATH
        shell: powershell

      - name: Run Selenium Script
        run: python send_report.py
